import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#eef6fb" },
  keyboardView: { flex: 1 },
  scrollContent: { flexGrow: 1, justifyContent: "center", padding: 20 },
  panel: { padding: 24, borderRadius: 28, backgroundColor: "#ffffff", shadowColor: "#0f172a", shadowOffset: { width: 0, height: 18 }, shadowOpacity: 0.12, shadowRadius: 32, elevation: 8 },
  dashboardPanel: { gap: 18 },
  badge: { alignSelf: "flex-start", paddingHorizontal: 12, paddingVertical: 6, borderRadius: 999, backgroundColor: "#0f766e", color: "#ffffff", overflow: "hidden", fontSize: 12, fontWeight: "700", letterSpacing: 1 },
  title: { marginTop: 18, fontSize: 28, fontWeight: "700", color: "#10263d" },
  subtitle: { marginTop: 8, fontSize: 16, lineHeight: 24, color: "#5b7089" },
  form: { marginTop: 12, gap: 12 },
  field: { gap: 8 },
  label: { fontSize: 14, fontWeight: "700", color: "#334155" },
  input: { height: 48, borderWidth: 1, borderColor: "#cbd5e1", borderRadius: 14, paddingHorizontal: 14, backgroundColor: "#ffffff", color: "#0f172a" },
  primaryButton: { height: 48, alignItems: "center", justifyContent: "center", borderRadius: 14, backgroundColor: "#0f766e" },
  primaryButtonText: { color: "#ffffff", fontSize: 16, fontWeight: "700" },
  secondaryButton: { height: 46, alignItems: "center", justifyContent: "center", borderRadius: 14, backgroundColor: "#e2e8f0" },
  secondaryButtonText: { color: "#0f172a", fontSize: 15, fontWeight: "700" },
  smallButton: { width: 72, height: 48, alignItems: "center", justifyContent: "center", borderRadius: 14, backgroundColor: "#e2e8f0" },
  smallButtonText: { color: "#0f172a", fontWeight: "800" },
  disabledButton: { opacity: 0.7 },
  error: { marginTop: 10, padding: 12, borderRadius: 14, overflow: "hidden", backgroundColor: "#fef2f2", color: "#b91c1c" },
  notice: { padding: 12, borderRadius: 14, overflow: "hidden", backgroundColor: "#ecfdf5", color: "#047857", fontWeight: "700" },
  operationGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  operationCard: { width: "48%", minHeight: 136, gap: 8, padding: 14, borderRadius: 18, backgroundColor: "#f8fafc", borderWidth: 1, borderColor: "#e2e8f0" },
  activeOperationCard: { backgroundColor: "#0f766e", borderColor: "#0f766e" },
  operationTag: { color: "#0f766e", fontSize: 12, fontWeight: "800" },
  operationTitle: { color: "#10263d", fontSize: 17, fontWeight: "800" },
  operationDescription: { color: "#64748b", fontSize: 13, lineHeight: 19 },
  activeOperationText: { color: "#ffffff" },
  detailCard: { gap: 12, padding: 18, borderRadius: 20, backgroundColor: "#ecfeff" },
  detailTag: { color: "#0f766e", fontSize: 12, fontWeight: "800" },
  sectionTitle: { fontSize: 20, fontWeight: "800", color: "#10263d" },
  detailDescription: { color: "#475569", fontSize: 15, lineHeight: 22 },
  inlineRow: { flexDirection: "row", gap: 10, alignItems: "center" },
  inlineInput: { flex: 1 },
  flexButton: { flex: 1 },
  summary: { color: "#475569", fontSize: 14, lineHeight: 20 },
  choiceList: { gap: 8 },
  choiceItem: { padding: 12, borderRadius: 14, backgroundColor: "#ffffff", borderWidth: 1, borderColor: "#dbe7ee" },
  activeChoiceItem: { backgroundColor: "#0f766e", borderColor: "#0f766e" },
  choiceTitle: { color: "#10263d", fontSize: 15, fontWeight: "800" },
  choiceSubtitle: { marginTop: 4, color: "#64748b", fontSize: 12, lineHeight: 18 },
  previewCard: { gap: 8, padding: 12, borderRadius: 14, backgroundColor: "#ffffff" },
  previewText: { color: "#475569", lineHeight: 20 }
});
